#!/usr/bin/env node
// Renders the Drakenhold sources to a browsable static site in build/web/.
//
// Usage: node render_web.mjs [OUT_DIR]
//
// Sibling of render.mjs and deliberately built on the same toolchain: mermaid
// fenced blocks -> static SVG (via mermaid-cli), markdown -> HTML (via marked).
// The PDF prints one long paginated document; the site publishes one page per
// source file with persistent navigation, which is what reference-during-play
// actually wants.
//
// Two things the site does that the PDF cannot:
//   - every location code in backticks (`FA.17`) becomes a link to that stub,
//     wherever in the corpus it is written;
//   - the region list is filterable from the keyboard.
//
// Diagrams are pre-rendered to inline SVG rather than shipped as mermaid plus a
// CDN script, so the site works offline once loaded and needs no third-party
// requests at the table.
//
// Scope: play content only — the setting outline, the 22 regions, the block
// documents and the setting relational diagram. Process documents (HANDOFF,
// PROCEDURES_AND_RULES, RECONCILIATION, DECISIONS, OPEN_QUESTIONS) are
// authoring instruments and are not
// published.
//
// This script never writes to or modifies any content file — only OUT_DIR.

import { execFileSync } from "node:child_process";
import {
  mkdtempSync, readFileSync, writeFileSync, rmSync, mkdirSync,
  existsSync, copyFileSync, readdirSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");
const OUT = path.resolve(process.argv[2] || path.join(REPO, "build", "web"));

const MMDC = path.join(HERE, "node_modules", ".bin", "mmdc");

function fail(message) {
  console.error(`web render failed: ${message}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Assets. Inline here so the site build stays a single file with no template
// directory to keep in sync.
// ---------------------------------------------------------------------------
const CSS = `/* Generated by scripts/build_web.sh — do not hand-edit. */
:root {
  --bg: #fbfaf7;
  --fg: #1e1c19;
  --muted: #6b655c;
  --rule: #d9d3c7;
  --accent: #7a3b1d;
  --panel: #f3f0e9;
  --sidebar-w: 20rem;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #161513;
    --fg: #e8e4dc;
    --muted: #9a9287;
    --rule: #34312c;
    --accent: #d98a5a;
    --panel: #1e1c19;
  }
}
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font-family: Georgia, "Iowan Old Style", "Times New Roman", serif;
  font-size: 17px;
  line-height: 1.6;
}

/* Sidebar */
.sidebar {
  position: fixed;
  top: 0; left: 0; bottom: 0;
  width: var(--sidebar-w);
  overflow-y: auto;
  padding: 1.5rem 1.25rem 3rem;
  background: var(--panel);
  border-right: 1px solid var(--rule);
}
.brand {
  display: block;
  font-size: 1.35rem;
  font-weight: 700;
  letter-spacing: 0.02em;
  text-decoration: none;
  color: var(--fg);
  margin-bottom: 0.85rem;
}
.nav-filter {
  width: 100%;
  padding: 0.4rem 0.55rem;
  margin-bottom: 1rem;
  font: inherit;
  font-size: 0.85rem;
  color: var(--fg);
  background: var(--bg);
  border: 1px solid var(--rule);
  border-radius: 3px;
}
.nav-group h2 {
  font-size: 0.72rem;
  text-transform: uppercase;
  letter-spacing: 0.12em;
  color: var(--muted);
  margin: 1.25rem 0 0.4rem;
  font-weight: 700;
}
.nav-group ul { list-style: none; margin: 0; padding: 0; }
.nav-group li { margin: 0; }
.nav-group a {
  display: block;
  padding: 0.22rem 0.4rem;
  font-size: 0.9rem;
  line-height: 1.35;
  color: var(--fg);
  text-decoration: none;
  border-radius: 3px;
}
.nav-group a:hover { background: var(--bg); color: var(--accent); }
.nav-group li.current > a {
  background: var(--bg);
  color: var(--accent);
  font-weight: 700;
  box-shadow: inset 2px 0 0 var(--accent);
}
.nav-toggle {
  display: none;
  position: fixed;
  top: 0.6rem; left: 0.6rem;
  z-index: 20;
  font-size: 1.2rem;
  line-height: 1;
  padding: 0.45rem 0.6rem;
  color: var(--fg);
  background: var(--panel);
  border: 1px solid var(--rule);
  border-radius: 4px;
  cursor: pointer;
}

/* Main column */
main {
  max-width: 46rem;
  margin: 0 auto;
  padding: 3rem 2rem 6rem;
  margin-left: var(--sidebar-w);
}
@media (min-width: 90rem) {
  main { margin-left: calc(var(--sidebar-w) + 4rem); }
}
h1 {
  font-size: 2rem;
  line-height: 1.2;
  margin: 0 0 1rem;
  padding-bottom: 0.3rem;
  border-bottom: 2px solid var(--rule);
}
h2 {
  font-size: 1.3rem;
  margin: 2.4rem 0 0.7rem;
  padding-bottom: 0.2rem;
  border-bottom: 1px solid var(--rule);
  letter-spacing: 0.02em;
}
h3 { font-size: 1.08rem; margin: 1.8rem 0 0.4rem; }
h3.stub { scroll-margin-top: 1.5rem; }
h3.stub > code {
  background: none;
  padding: 0;
  font-family: inherit;
  font-weight: 700;
  color: var(--accent);
}
p { margin: 0.7rem 0; }
a { color: var(--accent); }
code {
  font-family: ui-monospace, "SF Mono", "Courier New", monospace;
  font-size: 0.86em;
  background: var(--panel);
  padding: 0.08em 0.32em;
  border-radius: 3px;
}
a.code-ref { text-decoration: none; border-bottom: 1px dotted var(--accent); }
a.code-ref:hover code { background: var(--accent); color: var(--bg); }
table {
  border-collapse: collapse;
  width: 100%;
  margin: 1rem 0;
  font-size: 0.92rem;
  display: block;
  overflow-x: auto;
}
th, td {
  border: 1px solid var(--rule);
  padding: 0.4rem 0.6rem;
  text-align: left;
  vertical-align: top;
}
th { background: var(--panel); }
blockquote {
  margin: 1rem 0;
  padding-left: 1rem;
  border-left: 3px solid var(--rule);
  color: var(--muted);
}
hr { border: none; border-top: 1px solid var(--rule); margin: 2rem 0; }
.standfirst { font-size: 1.1rem; color: var(--muted); }
.index-list { columns: 2; column-gap: 2rem; }
@media (max-width: 40rem) { .index-list { columns: 1; } }

/* Diagrams: mermaid renders for a light ground, so it keeps one in both themes. */
.diagram {
  margin: 1.5rem 0;
  padding: 1rem;
  overflow-x: auto;
  text-align: center;
  background: #fdfdfb;
  border: 1px solid var(--rule);
  border-radius: 5px;
}
.diagram svg { max-width: 100%; height: auto; }
.diagram-error { color: #b00; font-style: italic; }

/* Footer */
.pager {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  margin-top: 3.5rem;
  padding-top: 1rem;
  border-top: 1px solid var(--rule);
  font-size: 0.9rem;
}
.pager a { text-decoration: none; }
.pager a:hover { text-decoration: underline; }
.source { color: var(--muted); font-size: 0.8rem; margin-top: 1.5rem; }

@media (max-width: 60rem) {
  .nav-toggle { display: block; }
  .sidebar { transform: translateX(-100%); transition: transform 0.18s ease; z-index: 15; }
  body.nav-open .sidebar { transform: none; }
  main { margin-left: 0; padding: 3.5rem 1.1rem 5rem; }
}
`;

const JS = `/* Generated by scripts/build_web.sh — do not hand-edit. */
(function () {
  var filter = document.getElementById("nav-filter");
  var items = Array.prototype.slice.call(document.querySelectorAll(".nav-group li"));

  if (filter) {
    filter.addEventListener("input", function () {
      var q = filter.value.trim().toLowerCase();
      items.forEach(function (li) {
        var a = li.querySelector("a");
        var hit = !q || (a && a.textContent.toLowerCase().indexOf(q) !== -1);
        li.style.display = hit ? "" : "none";
      });
    });
    filter.addEventListener("keydown", function (e) {
      if (e.key === "Escape") { filter.value = ""; filter.dispatchEvent(new Event("input")); filter.blur(); }
      if (e.key === "Enter") {
        var first = items.filter(function (li) { return li.style.display !== "none"; })[0];
        var a = first && first.querySelector("a");
        if (a) window.location.href = a.getAttribute("href");
      }
    });
  }

  // "/" focuses the filter, the way every reference site worth using does.
  document.addEventListener("keydown", function (e) {
    if (e.key === "/" && document.activeElement !== filter) {
      e.preventDefault();
      document.body.classList.add("nav-open");
      if (filter) { filter.focus(); filter.select(); }
    }
  });

  var toggle = document.querySelector(".nav-toggle");
  if (toggle) {
    toggle.addEventListener("click", function () {
      var open = document.body.classList.toggle("nav-open");
      toggle.setAttribute("aria-expanded", String(open));
    });
  }

  // Keep the current page visible in a long sidebar.
  var current = document.querySelector(".nav-group li.current");
  if (current && current.scrollIntoView) {
    current.scrollIntoView({ block: "center" });
  }
})();
`;

function read(p) {
  try {
    return readFileSync(p, "utf8");
  } catch {
    fail(`missing or unreadable source file: ${path.relative(REPO, p)}`);
  }
}

// ---------------------------------------------------------------------------
// Source manifest — mirrors build.py's section order.
// ---------------------------------------------------------------------------
const INDEX_ROW_RE = /^\|\s*[A-Z]{1,2}\s*\|.*\|\s*`([^`]+\.md)`\s*\|\s*$/;

function regionOrder() {
  const indexPath = path.join(REPO, "regions", "00_INDEX.md");
  const names = [];
  for (const line of read(indexPath).split("\n")) {
    const m = INDEX_ROW_RE.exec(line.trim());
    if (m) names.push(m[1]);
  }
  if (names.length === 0) fail(`no region rows parsed from regions/00_INDEX.md`);
  return names;
}

// Region display title, from the file's own "# `CODE Name`" line.
function titleOf(markdown, fallback) {
  const m = /^#\s+`?([^`\n]+)`?\s*$/m.exec(markdown);
  return m ? m[1].trim() : fallback;
}

function slugOf(fileName) {
  return fileName.replace(/\.md$/, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const pages = [];

// 1. The setting outline.
{
  const p = path.join(REPO, "Drakenhold_Setting_Outline.md");
  const md = read(p);
  // The outline's own H1 is "DRAKENHOLD", which is useless as a nav label.
  pages.push({ slug: "setting-outline", title: "Setting Outline",
               group: "The Setting", md, source: path.relative(REPO, p) });
}

// 2. The regions, in 00_INDEX.md order.
for (const name of regionOrder()) {
  const p = path.join(REPO, "regions", name);
  const md = read(p);
  pages.push({ slug: slugOf(name), title: titleOf(md, name),
               group: "Regions", md, source: path.relative(REPO, p) });
}

// 3. The block documents, in their standing order.
const BLOCK_ORDER = [
  "FIRST_LEVEL_BLOCK.md", "PEAK_1_BLOCK.md", "PEAK_2_BLOCK.md",
  "PEAK_3_BLOCK.md", "I_AND_J_BLOCK.md",
];
for (const name of BLOCK_ORDER) {
  const p = path.join(REPO, "blocks", name);
  if (!existsSync(p)) continue;
  const md = read(p);
  // Block H1s are long all-caps banners; the file name makes the better label.
  const label = name.replace(/\.md$/, "").split("_")
    .map((w) => (/^[A-Z]{1,2}$/.test(w) || /^\d+$/.test(w) ? w : w.charAt(0) + w.slice(1).toLowerCase()))
    .join(" ");
  pages.push({ slug: slugOf(name), title: label,
               group: "Blocks", md, source: path.relative(REPO, p) });
}

// 4. The setting-level relational diagram.
{
  const p = path.join(REPO, "diagrams", "Drakenhold_Relational_Diagram.md");
  const md = read(p);
  pages.push({ slug: "relational-diagram", title: "Setting Relational Diagram",
               group: "Diagrams", md, source: path.relative(REPO, p) });
}

// ---------------------------------------------------------------------------
// Location code index — code -> page slug, built from stub headings.
// Same shape as check.py's STUB_HEADING_RE, so the site and the checks agree
// on what counts as a defined location.
// ---------------------------------------------------------------------------
const STUB_HEADING_RE = /^### `([A-Z]{1,2}\.[0-9]+[a-z]?) ([^`]+)`/;

const codeIndex = new Map();   // "A.1" -> { slug, name }
for (const page of pages) {
  for (const line of page.md.split("\n")) {
    const m = STUB_HEADING_RE.exec(line);
    if (m && !codeIndex.has(m[1])) {
      codeIndex.set(m[1], { slug: page.slug, name: m[2].trim() });
    }
  }
}

// ---------------------------------------------------------------------------
// Mermaid -> inline SVG, via the same mermaid-cli the PDF uses.
// ---------------------------------------------------------------------------
const MERMAID_BLOCK_RE = /```mermaid\n([\s\S]*?)```/g;

const workDir = mkdtempSync(path.join(tmpdir(), "drakenhold-web-"));
const puppeteerConfigPath = path.join(workDir, "puppeteer-config.json");
writeFileSync(puppeteerConfigPath, JSON.stringify({ args: ["--no-sandbox"] }));

let diagramCount = 0;
let renderFailures = 0;

function renderMermaidToSvg(code) {
  diagramCount += 1;
  const inFile = path.join(workDir, `diagram-${diagramCount}.mmd`);
  const outFile = path.join(workDir, `diagram-${diagramCount}.svg`);
  writeFileSync(inFile, code);
  try {
    execFileSync(MMDC, ["-i", inFile, "-o", outFile, "-p", puppeteerConfigPath, "-b", "transparent"], {
      stdio: ["ignore", "ignore", "pipe"],
    });
  } catch (e) {
    renderFailures += 1;
    console.error(`  diagram ${diagramCount}: mermaid render failed — ${e.stderr?.toString().trim() || e.message}`);
    return `<div class="diagram-error">[diagram ${diagramCount} failed to render — see build log]</div>`;
  }
  return `<div class="diagram">${readFileSync(outFile, "utf8")}</div>`;
}

// ---------------------------------------------------------------------------
// HTML assembly
// ---------------------------------------------------------------------------
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
          .replace(/"/g, "&quot;");
}

const CODE_SPAN_RE = /<code>([A-Z]{1,2}\.[0-9]+[a-z]?)<\/code>/g;

// Post-process marked's output, line by line:
//   - stub headings get an id, so codes are linkable targets;
//   - every other code span that names a known location becomes a link.
// marked emits each heading on its own line, which is what makes the
// "don't self-link a heading" rule cheap to enforce.
function linkifyAndAnchor(html, currentSlug) {
  const out = [];
  for (const line of html.split("\n")) {
    const headingMatch = /^<h3[^>]*><code>([A-Z]{1,2}\.[0-9]+[a-z]?) /.exec(line);
    if (headingMatch) {
      const code = headingMatch[1];
      let anchored = line.replace(/^<h3([^>]*)>/, `<h3$1 id="${code}" class="stub">`);
      // Link any *other* codes in the heading, but not the stub's own code.
      let seenSelf = false;
      anchored = anchored.replace(CODE_SPAN_RE, (whole, c) => {
        if (c === code && !seenSelf) { seenSelf = true; return whole; }
        return linkFor(c, whole, currentSlug);
      });
      out.push(anchored);
      continue;
    }
    out.push(line.replace(CODE_SPAN_RE, (whole, c) => linkFor(c, whole, currentSlug)));
  }
  return out.join("\n");
}

function linkFor(code, whole, currentSlug) {
  const target = codeIndex.get(code);
  if (!target) return whole;   // undefined code — leave it plain, M1 will catch it
  const href = target.slug === currentSlug ? `#${code}` : `${target.slug}.html#${code}`;
  const title = escapeHtml(`${code} ${target.name}`);
  return `<a class="code-ref" href="${href}" title="${title}">${whole}</a>`;
}

function navHtml(currentSlug) {
  const groups = [];
  for (const page of pages) {
    let g = groups.find((x) => x.name === page.group);
    if (!g) { g = { name: page.group, items: [] }; groups.push(g); }
    g.items.push(page);
  }
  const parts = [`<nav class="sidebar" aria-label="Contents">`];
  parts.push(`<a class="brand" href="index.html">Drakenhold</a>`);
  parts.push(
    `<input type="search" id="nav-filter" class="nav-filter" placeholder="Filter (press /)" ` +
    `aria-label="Filter contents" autocomplete="off">`
  );
  for (const g of groups) {
    parts.push(`<div class="nav-group"><h2>${escapeHtml(g.name)}</h2><ul>`);
    for (const p of g.items) {
      const cls = p.slug === currentSlug ? ` class="current"` : "";
      parts.push(`<li${cls}><a href="${p.slug}.html">${escapeHtml(p.title)}</a></li>`);
    }
    parts.push(`</ul></div>`);
  }
  parts.push(`<div class="nav-group"><h2>Print</h2><ul>`);
  parts.push(`<li><a href="Drakenhold_Playbook.pdf">The Playbook, as PDF</a></li>`);
  parts.push(`</ul></div>`);
  parts.push(`</nav>`);
  return parts.join("\n");
}

function shell({ title, currentSlug, body, footer = "" }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)} · Drakenhold</title>
<link rel="stylesheet" href="assets/site.css">
</head>
<body>
<button class="nav-toggle" aria-label="Contents" aria-expanded="false">☰</button>
${navHtml(currentSlug)}
<main>
${body}
${footer}
</main>
<script src="assets/site.js" defer></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------
mkdirSync(path.join(OUT, "assets"), { recursive: true });

console.log(`Rendering ${pages.length} page(s) to ${path.relative(REPO, OUT)}/ ...`);

pages.forEach((page, i) => {
  const withDiagrams = page.md.replace(MERMAID_BLOCK_RE, (_m, code) => renderMermaidToSvg(code));
  const body = linkifyAndAnchor(marked.parse(withDiagrams), page.slug);

  const prev = pages[i - 1];
  const next = pages[i + 1];
  const footerParts = [`<nav class="pager" aria-label="Previous and next">`];
  footerParts.push(prev
    ? `<a class="prev" href="${prev.slug}.html">← ${escapeHtml(prev.title)}</a>`
    : `<span></span>`);
  footerParts.push(next
    ? `<a class="next" href="${next.slug}.html">${escapeHtml(next.title)} →</a>`
    : `<span></span>`);
  footerParts.push(`</nav>`);
  footerParts.push(`<p class="source">Source: <code>${escapeHtml(page.source)}</code></p>`);

  writeFileSync(
    path.join(OUT, `${page.slug}.html`),
    shell({ title: page.title, currentSlug: page.slug, body, footer: footerParts.join("\n") }),
    "utf8",
  );
});

// Index page.
{
  const groups = [];
  for (const page of pages) {
    let g = groups.find((x) => x.name === page.group);
    if (!g) { g = { name: page.group, items: [] }; groups.push(g); }
    g.items.push(page);
  }
  const parts = [];
  parts.push(`<h1>Drakenhold</h1>`);
  parts.push(
    `<p class="standfirst">A ruined dwarven mountain hold in three peaks, occupied by a red ` +
    `dragon, robbed by whoever dares. The spine is extraction and survival, not a boss fight.</p>`
  );
  parts.push(
    `<p>This is the browsable reference build, assembled from the source files by ` +
    `<code>scripts/build_web.sh</code>. Every location code in the text — <code>FA.17</code>, ` +
    `<code>A.20</code> — is a link to the stub it names, anywhere in the corpus. ` +
    `The same sources print as <a href="Drakenhold_Playbook.pdf">a paginated PDF</a>.</p>`
  );
  for (const g of groups) {
    parts.push(`<h2>${escapeHtml(g.name)}</h2><ul class="index-list">`);
    for (const p of g.items) {
      parts.push(`<li><a href="${p.slug}.html">${escapeHtml(p.title)}</a></li>`);
    }
    parts.push(`</ul>`);
  }
  parts.push(
    `<p class="source">${pages.length} pages · ${codeIndex.size} locations indexed · ` +
    `${diagramCount} diagrams rendered.</p>`
  );
  writeFileSync(
    path.join(OUT, "index.html"),
    shell({ title: "Contents", currentSlug: "index", body: parts.join("\n") }),
    "utf8",
  );
}

// Assets.
writeFileSync(path.join(OUT, "assets", "site.css"), CSS, "utf8");
writeFileSync(path.join(OUT, "assets", "site.js"), JS, "utf8");

// Carry the PDF alongside the site if it has been built.
const pdfSrc = path.join(REPO, "build", "Drakenhold_Playbook.pdf");
if (existsSync(pdfSrc)) {
  copyFileSync(pdfSrc, path.join(OUT, "Drakenhold_Playbook.pdf"));
  console.log("  bundled Drakenhold_Playbook.pdf alongside the site");
} else {
  console.log("  note: build/Drakenhold_Playbook.pdf not present — the PDF link will 404");
}

rmSync(workDir, { recursive: true, force: true });

if (renderFailures > 0) {
  fail(`${renderFailures} of ${diagramCount} mermaid diagram(s) failed to render`);
}

console.log(
  `Wrote ${readdirSync(OUT).length} entries to ${path.relative(REPO, OUT)}/ ` +
  `(${pages.length} pages, ${codeIndex.size} location codes indexed, ${diagramCount} diagrams)`
);
