#!/usr/bin/env python3
"""
Assemble the Drakenhold Setting Playbook from source files, in the section
order defined by Setting_Playbook_Template.md.

Usage:
    build.py            assemble to build/Drakenhold_Playbook.md
    build.py OUT_PATH    assemble to a custom path

Assembly is mechanical: source files are concatenated verbatim, in a fixed
order. No content is generated or altered. A missing or unreadable source
file is a build failure, reported to stderr with the offending path; no
output is written.

Section mapping:
  SETTING .. STANDING MYSTERIES    -> Drakenhold_Setting_Outline.md (title,
                                       tagline and Overview; its title/tagline
                                       serve as SETTING) followed by
                                       outlines/*.md in numeric order, verbatim.
                                       The outline index's `## SECTIONS`
                                       navigation table is dropped; the numeric
                                       prefixes carry the template's order.
  REGIONAL GAZETTEER                -> each region file, whole, in the order
                                       given by regions/00_INDEX.md. Each
                                       region file already carries its own
                                       Gazetteer fields, its Locations, and
                                       (once authored) its own Relational
                                       Diagram together, so nothing is split
                                       out of them.
  RELATIONAL DIAGRAMS               -> diagrams/Drakenhold_Relational_Diagram.md,
                                       which explains the five tiers and hosts
                                       the tier-1 and tier-2 graphs. Tier-3 and
                                       tier-4 graphs are hosted by the region
                                       files above.

Every diagram is its own file in diagrams/. A host document carries a marker
line — <!-- DIAGRAM: T3_FA.md --> — and assembly replaces it with that file's
contents; see scripts/diagrams.py. A marker naming a file that is not there is
a build failure like any other missing source.
  LOCATIONS                         -> omitted; already embedded per-region.

This script never writes to or modifies any content file — only the
assembled output path.
"""

import re
import sys
from pathlib import Path

import diagrams

REPO = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / "build" / "Drakenhold_Playbook.md"

OUTLINE = REPO / "Drakenhold_Setting_Outline.md"
OUTLINE_DIR = REPO / "outlines"
SETTING_DIAGRAM = REPO / "diagrams" / "Drakenhold_Relational_Diagram.md"
INDEX = REPO / "regions" / "00_INDEX.md"

_INDEX_ROW_RE = re.compile(r'^\|\s*[A-Z]{1,2}\s*\|.*\|\s*`([^`]+\.md)`\s*\|\s*$')


def region_order() -> list[str]:
    """Region file names, in 00_INDEX.md's table order."""
    names: list[str] = []
    for line in INDEX.read_text(encoding='utf-8').splitlines():
        m = _INDEX_ROW_RE.match(line.strip())
        if m:
            names.append(m.group(1))
    return names


def outline_index() -> str:
    """The outline index down to, but excluding, its `## SECTIONS` navigation
    table. That table points at outlines/ and is an authoring instrument, not
    play content."""
    text = read_or_fail(OUTLINE)
    marker = "\n## SECTIONS\n"
    if marker in text:
        text = text[:text.index(marker)]
    return text.rstrip().rstrip("-").rstrip() + "\n"


def outline_sections() -> list[Path]:
    """outlines/NN_FIELD.md in numeric order. The order is the template's."""
    paths = sorted(OUTLINE_DIR.glob("[0-9][0-9]_*.md"))
    if not paths:
        print(f"build failed: no outline sections found in {OUTLINE_DIR}",
              file=sys.stderr)
        sys.exit(1)
    return paths


def read_or_fail(path: Path) -> str:
    if not path.is_file():
        print(f"build failed: missing source file: {path}", file=sys.stderr)
        sys.exit(1)
    try:
        text = path.read_text(encoding='utf-8')
    except OSError as e:
        print(f"build failed: cannot read {path}: {e}", file=sys.stderr)
        sys.exit(1)
    try:
        return diagrams.splice(text, source=str(path))
    except FileNotFoundError as e:
        print(f"build failed: {e}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT

    region_files = region_order()
    if not region_files:
        print(f"build failed: no region rows parsed from {INDEX}", file=sys.stderr)
        sys.exit(1)

    parts: list[str] = []
    parts.append("<!-- Generated by scripts/build.sh — do not hand-edit. -->\n")
    parts.append(outline_index().rstrip() + "\n")
    for section_path in outline_sections():
        parts.append("\n---\n\n" + read_or_fail(section_path).rstrip() + "\n")

    parts.append("\n---\n\n## REGIONAL GAZETTEER\n")
    for name in region_files:
        region_path = REPO / "regions" / name
        parts.append("\n---\n\n" + read_or_fail(region_path).rstrip() + "\n")

    parts.append("\n---\n\n## RELATIONAL DIAGRAMS\n")
    parts.append("\n" + read_or_fail(SETTING_DIAGRAM).rstrip() + "\n")
    parts.append(
        "\n*Tier-3 and tier-4 diagrams are embedded in each region file's own "
        "REGION RELATIONAL DIAGRAM section above.*\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(parts), encoding='utf-8')

    total_lines = sum(p.count("\n") for p in parts)
    print(
        f"Assembled {len(region_files)} regions + "
        f"{len(outline_sections())} outline sections + diagram "
        f"-> {out_path.relative_to(REPO)} ({total_lines} lines)"
    )


if __name__ == "__main__":
    main()
