#!/usr/bin/env python3
"""
Assemble the Drakenhold Setting Playbook from source files, in the section
order defined by Setting_Playbook_Template.md.

Usage:
    build.py            assemble to build/Drakenhold_Playbook.md
    build.py OUT_PATH    assemble to a custom path

Assembly is mechanical: source files are concatenated verbatim, in a fixed
order. No content is generated or altered. A missing or unreadable source
file is a build failure, reported to stderr with the offending path; no
output is written.

Section mapping:
  SETTING .. UNANSWERED QUESTIONS  -> Drakenhold_Setting_Outline.md, verbatim
                                       (its own title/tagline serve as SETTING;
                                       its own headings already match the
                                       template's order exactly)
  REGIONAL GAZETTEER                -> each region file, whole, in the order
                                       given by regions/00_INDEX.md. Each
                                       region file already carries its own
                                       Gazetteer fields, its Locations, and
                                       (once authored) its own Relational
                                       Diagram together, so nothing is split
                                       out of them.
  RELATIONAL DIAGRAMS               -> diagrams/Drakenhold_Relational_Diagram.md,
                                       the one setting-level diagram. Per-
                                       region diagrams live inside their
                                       region files above, not here.
  LOCATIONS                         -> omitted; already embedded per-region.

This script never writes to or modifies any content file — only the
assembled output path.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / "build" / "Drakenhold_Playbook.md"

OUTLINE = REPO / "Drakenhold_Setting_Outline.md"
SETTING_DIAGRAM = REPO / "diagrams" / "Drakenhold_Relational_Diagram.md"
INDEX = REPO / "regions" / "00_INDEX.md"

_INDEX_ROW_RE = re.compile(r'^\|\s*[A-Z]{1,2}\s*\|.*\|\s*`([^`]+\.md)`\s*\|\s*$')


def region_order() -> list[str]:
    """Region file names, in 00_INDEX.md's table order."""
    names: list[str] = []
    for line in INDEX.read_text(encoding='utf-8').splitlines():
        m = _INDEX_ROW_RE.match(line.strip())
        if m:
            names.append(m.group(1))
    return names


def read_or_fail(path: Path) -> str:
    if not path.is_file():
        print(f"build failed: missing source file: {path}", file=sys.stderr)
        sys.exit(1)
    try:
        return path.read_text(encoding='utf-8')
    except OSError as e:
        print(f"build failed: cannot read {path}: {e}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT

    region_files = region_order()
    if not region_files:
        print(f"build failed: no region rows parsed from {INDEX}", file=sys.stderr)
        sys.exit(1)

    parts: list[str] = []
    parts.append("<!-- Generated by scripts/build.sh — do not hand-edit. -->\n")
    parts.append(read_or_fail(OUTLINE).rstrip() + "\n")

    parts.append("\n---\n\n## REGIONAL GAZETTEER\n")
    for name in region_files:
        region_path = REPO / "regions" / name
        parts.append("\n---\n\n" + read_or_fail(region_path).rstrip() + "\n")

    parts.append("\n---\n\n## RELATIONAL DIAGRAMS\n")
    parts.append("\n" + read_or_fail(SETTING_DIAGRAM).rstrip() + "\n")
    parts.append(
        "\n*Per-region diagrams are embedded in each region file's own "
        "REGION RELATIONAL DIAGRAM section above.*\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(parts), encoding='utf-8')

    total_lines = sum(p.count("\n") for p in parts)
    print(
        f"Assembled {len(region_files)} regions + setting outline + diagram "
        f"-> {out_path.relative_to(REPO)} ({total_lines} lines)"
    )


if __name__ == "__main__":
    main()
